/**
 * Style constants for VoteModal component
 * Following Single Responsibility Principle - only contains style definitions
 */

export const modalStyles = {
  overlay: 'fixed inset-0 z-50 flex items-center justify-center p-4',
  backdrop: 'absolute inset-0 bg-black/60 backdrop-blur-sm',
  modal: 'relative bg-white rounded-3xl shadow-2xl max-w-md w-full max-h-[90vh] overflow-y-auto animate-fade-in-up',
  header: 'sticky top-0 bg-white border-b border-gray-100 px-6 py-4 flex items-center justify-between rounded-t-3xl z-10',
  headerTitle: 'font-headline text-subhead font-bold text-navy-blue',
  closeButton: 'w-10 h-10 rounded-xl bg-gray-bg hover:bg-gray-100 flex items-center justify-center text-warm-grey hover:text-navy-blue transition-colors',
  closeIcon: 'w-4 h-4',
  content: 'px-6 py-6',
  successContainer: 'space-y-6',
  successIconContainer: 'w-20 h-20 bg-gold rounded-full flex items-center justify-center mx-auto mb-4',
  successIcon: 'w-10 h-10 text-white',
  successTitle: 'text-lg font-black text-navy-blue mb-2',
  successMessage: 'text-sm text-warm-grey',
  loadingContainer: 'text-center py-8',
  loadingSpinner: 'inline-block w-8 h-8 border-2 border-gold border-t-transparent rounded-full animate-spin mb-4',
  loadingText: 'text-sm text-warm-grey',
  errorContainer: 'bg-red-50 border-2 border-red-200 rounded-xl p-4 mb-4',
  errorContent: 'flex items-start gap-3',
  errorIcon: 'w-5 h-5 text-red-600 flex-shrink-0 mt-0.5',
  errorTextContainer: 'text-right flex-1',
  errorTitle: 'text-sm font-bold text-red-800 mb-1',
  errorMessage: 'text-xs text-red-600',
  phoneInput: 'w-full px-4 py-3 rounded-xl border-2 border-gray-200 text-navy-blue placeholder:text-warm-grey focus:border-gold focus:outline-none transition-colors',
  phoneInputError: 'border-red-300 focus:border-red-500',
  neighborhoodCard: 'bg-white rounded-2xl p-4 border-2 border-gold/20',
  neighborhoodCardContent: 'flex items-center gap-3',
  neighborhoodIcon: 'w-12 h-12 bg-gold/10 rounded-xl flex items-center justify-center text-2xl',
  neighborhoodInfo: 'flex-1 text-right',
  neighborhoodName: 'font-black text-navy-blue text-lg',
  neighborhoodLocation: 'text-xs text-warm-grey',
  privacyContainer: 'bg-gray-bg border border-gray-200 rounded-xl p-4',
  privacyContent: 'flex items-start gap-3',
  privacyIcon: 'w-4 h-4 text-gold flex-shrink-0 mt-0.5',
  privacyText: 'text-right flex-1',
  privacyMessage: 'text-xs text-warm-grey leading-relaxed',
  voteErrorContainer: 'bg-red-50 border-2 border-red-200 rounded-xl p-4',
  voteErrorContent: 'flex items-start gap-3',
  voteErrorIcon: 'w-5 h-5 text-red-600 flex-shrink-0 mt-0.5',
  voteErrorText: 'text-right flex-1',
  voteErrorTitle: 'text-sm font-bold text-red-800',
  buttonsContainer: 'space-y-3',
  voteButton: 'font-cta text-cta w-full py-3 bg-gold text-white rounded-xl font-normal hover:shadow-lg hover:shadow-gold/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2',
  voteButtonSpinner: 'inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin',
  voteButtonIcon: 'w-3 h-3',
  cancelButton: 'w-full py-3 bg-white border-2 border-gray-200 text-navy-blue rounded-xl font-bold text-base hover:border-gold hover:bg-gray-bg transition-all disabled:opacity-50 disabled:cursor-not-allowed',
} as const;
